### Alumno: *Juan Alberto Peñalver Alvarez*

# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [6]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [7]:
### [your code here]
print(np.__version__)
print(np.show_config())

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [8]:
### [your code here]
a = np.random.random((2,3,5))
a

array([[[0.05768547, 0.53334389, 0.54475591, 0.08800184, 0.868481  ],
        [0.33054637, 0.25504765, 0.4866673 , 0.06431487, 0.53765246],
        [0.43640325, 0.2507604 , 0.80626866, 0.24617294, 0.4536015 ]],

       [[0.19289293, 0.05018815, 0.62298169, 0.62991681, 0.47137888],
        [0.89917209, 0.73982449, 0.36520514, 0.16821774, 0.18912143],
        [0.1339409 , 0.01550372, 0.1941336 , 0.00989333, 0.6127808 ]]])


### 4. Print a.


In [9]:
### [your code here]
print(a)

[[[0.05768547 0.53334389 0.54475591 0.08800184 0.868481  ]
  [0.33054637 0.25504765 0.4866673  0.06431487 0.53765246]
  [0.43640325 0.2507604  0.80626866 0.24617294 0.4536015 ]]

 [[0.19289293 0.05018815 0.62298169 0.62991681 0.47137888]
  [0.89917209 0.73982449 0.36520514 0.16821774 0.18912143]
  [0.1339409  0.01550372 0.1941336  0.00989333 0.6127808 ]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [10]:
### [your code here]
b = np.ones((5,2,3))


### 6. Print b.


In [11]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [12]:
### [your code here]
if a.size == b.size:
  print("a and b have the same size")
else:
  print("a and b have different sizes")

a and b have the same size



### 8. Are you able to add a and b? Why or why not?


In [13]:
### [your code here]
try:
  c = a + b
except ValueError as e:
  print(e)

print()
print("No se pueden sumar porque tienen diferentes dimensiones")

print("a.shape = ", a.shape)
print("b.shape = ", b.shape)

print("Las dimensiones están en distinto orden.")

print("a →  [ 2 , 3 , 5 ]")
print("b →  [ 5 , 2 , 3 ]")

print(" Ahora, cuando NumPy intenta sumar: ")
print("  * Compara de derecha a izquierda. ")
print("  * Cada par de dimensiones debe ser iguales o una debe ser 1. ")


operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

No se pueden sumar porque tienen diferentes dimensiones
a.shape =  (2, 3, 5)
b.shape =  (5, 2, 3)
Las dimensiones están en distinto orden.
a →  [ 2 , 3 , 5 ]
b →  [ 5 , 2 , 3 ]
 Ahora, cuando NumPy intenta sumar: 
  * Compara de derecha a izquierda. 
  * Cada par de dimensiones debe ser iguales o una debe ser 1. 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [14]:
### [your code here]
c = b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [15]:
### [your code here]
d = a + c
d

array([[[1.05768547, 1.53334389, 1.54475591, 1.08800184, 1.868481  ],
        [1.33054637, 1.25504765, 1.4866673 , 1.06431487, 1.53765246],
        [1.43640325, 1.2507604 , 1.80626866, 1.24617294, 1.4536015 ]],

       [[1.19289293, 1.05018815, 1.62298169, 1.62991681, 1.47137888],
        [1.89917209, 1.73982449, 1.36520514, 1.16821774, 1.18912143],
        [1.1339409 , 1.01550372, 1.1941336 , 1.00989333, 1.6127808 ]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [16]:
### [your code here]
print("a = ", a)
print()
print("d = ", d)
print()
print("Los valores entre cada uno de los valores de a y d es 1, ")
print("ya que, d = a + c, y c está formada solamente por 1's.")

a =  [[[0.05768547 0.53334389 0.54475591 0.08800184 0.868481  ]
  [0.33054637 0.25504765 0.4866673  0.06431487 0.53765246]
  [0.43640325 0.2507604  0.80626866 0.24617294 0.4536015 ]]

 [[0.19289293 0.05018815 0.62298169 0.62991681 0.47137888]
  [0.89917209 0.73982449 0.36520514 0.16821774 0.18912143]
  [0.1339409  0.01550372 0.1941336  0.00989333 0.6127808 ]]]

d =  [[[1.05768547 1.53334389 1.54475591 1.08800184 1.868481  ]
  [1.33054637 1.25504765 1.4866673  1.06431487 1.53765246]
  [1.43640325 1.2507604  1.80626866 1.24617294 1.4536015 ]]

 [[1.19289293 1.05018815 1.62298169 1.62991681 1.47137888]
  [1.89917209 1.73982449 1.36520514 1.16821774 1.18912143]
  [1.1339409  1.01550372 1.1941336  1.00989333 1.6127808 ]]]

Los valores entre cada uno de los valores de a y d es 1, 
ya que, d = a + c, y c está formada solamente por 1's.



### 12. Multiply a and c. Assign the result to e.


In [17]:
### [your code here]
e = a * c
e

array([[[0.05768547, 0.53334389, 0.54475591, 0.08800184, 0.868481  ],
        [0.33054637, 0.25504765, 0.4866673 , 0.06431487, 0.53765246],
        [0.43640325, 0.2507604 , 0.80626866, 0.24617294, 0.4536015 ]],

       [[0.19289293, 0.05018815, 0.62298169, 0.62991681, 0.47137888],
        [0.89917209, 0.73982449, 0.36520514, 0.16821774, 0.18912143],
        [0.1339409 , 0.01550372, 0.1941336 , 0.00989333, 0.6127808 ]]])



### 13. Does e equal to a? Why or why not?


In [18]:
### [your code here]
print(e == a)
print()
print("Sí, porque cada uno de sus valores es True, es decir, son iguales comparandolos uno a uno.")

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]

Sí, porque cada uno de sus valores es True, es decir, son iguales comparandolos uno a uno.




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [19]:
### [your code here]
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print("d_max = ", d_max)
print("d_min = ", d_min)
print("d_mean = ", d_mean)


d_max =  1.8991720899658753
d_min =  1.0098933341751475
d_mean =  1.3751618401140209



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [23]:
### [your code here]
f = np.empty(d.shape)

print("Shape de f:", f.shape)
print("f (contenido inicial):")
print(f)


Shape de f: (2, 3, 5)
f (contenido inicial):
[[[0.05768547 0.53334389 0.54475591 0.08800184 0.868481  ]
  [0.33054637 0.25504765 0.4866673  0.06431487 0.53765246]
  [0.43640325 0.2507604  0.80626866 0.24617294 0.4536015 ]]

 [[0.19289293 0.05018815 0.62298169 0.62991681 0.47137888]
  [0.89917209 0.73982449 0.36520514 0.16821774 0.18912143]
  [0.1339409  0.01550372 0.1941336  0.00989333 0.6127808 ]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [ ]:
### [your code here]
f = np.empty(d.shape)
print(f)

d_min = d.min()
d_mean = d.mean()
d_max = d.max()

print("d_min = ", d_min)
print("d_mean = ", d_mean)
print("d_max = ", d_max)

for i in range(d.shape[0]):       # primer eje
    for j in range(d.shape[1]):   # segundo eje
        for k in range(d.shape[2]):  # tercer eje
            value = d[i, j, k]

            if value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100
            elif value == d_mean:
                f[i, j, k] = 50
            elif d_min < value < d_mean:
                f[i, j, k] = 25
            elif d_mean < value < d_max:
                f[i, j, k] = 75

print(np.unique(f))
print()
print(f)






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [36]:
### [your code here]
f = np.empty(d.shape)

d_min = d.min()
d_mean = d.mean()
d_max = d.max()

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100
            elif value == d_mean:
                f[i, j, k] = 50
            elif d_min < value < d_mean:
                f[i, j, k] = 25
            else:
                f[i, j, k] = 75

print("d =")
print(d)
print("\nExpected f =")
print(f)


d =
[[[1.05768547 1.53334389 1.54475591 1.08800184 1.868481  ]
  [1.33054637 1.25504765 1.4866673  1.06431487 1.53765246]
  [1.43640325 1.2507604  1.80626866 1.24617294 1.4536015 ]]

 [[1.19289293 1.05018815 1.62298169 1.62991681 1.47137888]
  [1.89917209 1.73982449 1.36520514 1.16821774 1.18912143]
  [1.1339409  1.01550372 1.1941336  1.00989333 1.6127808 ]]]

Expected f =
[[[ 25.  75.  75.  25.  75.]
  [ 25.  25.  75.  25.  75.]
  [ 75.  25.  75.  25.  75.]]

 [[ 25.  25.  75.  75.  75.]
  [100.  75.  25.  25.  25.]
  [ 25.  25.  25.   0.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [38]:
### [your code here]
g = np.empty(d.shape, dtype=str)  # crea un array vacío de strings

d_min = d.min()
d_mean = d.mean()
d_max = d.max()

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_min:
                g[i, j, k] = "A"
            elif value == d_max:
                g[i, j, k] = "E"
            elif value == d_mean:
                g[i, j, k] = "C"
            elif d_min < value < d_mean:
                g[i, j, k] = "B"
            else:  # d_mean < value < d_max
                g[i, j, k] = "D"

print("d =")
print(d)
print("\nExpected g =")
print(g)

d =
[[[1.05768547 1.53334389 1.54475591 1.08800184 1.868481  ]
  [1.33054637 1.25504765 1.4866673  1.06431487 1.53765246]
  [1.43640325 1.2507604  1.80626866 1.24617294 1.4536015 ]]

 [[1.19289293 1.05018815 1.62298169 1.62991681 1.47137888]
  [1.89917209 1.73982449 1.36520514 1.16821774 1.18912143]
  [1.1339409  1.01550372 1.1941336  1.00989333 1.6127808 ]]]

Expected g =
[[['B' 'D' 'D' 'B' 'D']
  ['B' 'B' 'D' 'B' 'D']
  ['D' 'B' 'D' 'B' 'D']]

 [['B' 'B' 'D' 'D' 'D']
  ['E' 'D' 'B' 'B' 'B']
  ['B' 'B' 'B' 'A' 'D']]]
